fos_rest:
    view:
        formats:
            json: true
            rss: false
            xml: true
    routing_loader:
        default_format: json

bazinga_hateoas:
    metadata:
        cache:                file
        file_cache:
            dir:              %kernel.cache_dir%/hateoas

nelmio_api_doc: ~
