index:
    path: /
    defaults : { _controller: ArdemisMainBundle:Main:index }


_ArdemisMainBundleAdminControllers:
    resource: "@ArdemisMainBundle/Controller/Admin"
    type: annotation
    prefix:   /admin


_ArdemisMainBundleApi:
    resource: "@ArdemisMainBundle/Resources/config/routing/api.yml"
    type: rest
    prefix:   /api
